In [1]:
import pandas as pd

In [20]:
kosdaq_df1 = pd.read_csv('../data/Kind_Data/코스닥_881_(2015~2024).csv')
kosdaq_df1.head()

,회사명,종목코드,상장일,상장유형,증권구분,업종,국적,상장주선인,액면가 (원),공모가 (원),공모금액 (천원),주요제품,최초상장주식수 (주)
0,파인메딕스,387570,2024-12-26,신규상장,주권,의료용 기기 제조업,대한민국,한국투자증권(주),100,"10,000","9,000,000","인젝터, 스네어, 나이프, 포셉 등 내시경용 시술기구","5,625,900"
1,쓰리에이로직스,177900,2024-12-24,신규상장,주권,반도체 제조업,대한민국,"신한투자증권 주식회사,미래에셋증권 주식회사",500,"11,000","20,431,400",NFC/IoT SoC 및 모듈,"9,286,800"
2,신한제14호스팩,487360,2024-12-23,신규상장,주권,금융 지원 서비스업,대한민국,신한투자증권 주식회사,100,"2,000","10,000,000",금융 지원 서비스업,"5,640,000"
3,키움제10호스팩,487720,2024-12-20,신규상장,주권,금융 지원 서비스업,대한민국,키움증권(주),100,"2,000","7,800,000",기업 인수합병,"4,230,000"
4,온코닉테라퓨틱스,476060,2024-12-19,신규상장,주권,자연과학 및 공학 연구개발업,대한민국,엔에이치투자증권주식회사,500,"13,000","20,150,000","자큐보정(Zastaprazan, 소화기질환 신약), Nesuparib(표적항암제 신약)","10,803,960"

In [21]:
kosdaq_df1.columns

Index(['회사명', '종목코드', '상장일', '상장유형', '증권구분', '업종', '국적', '상장주선인', '액면가 (원)',
       '공모가 (원)', '공모금액 (천원)', '주요제품', '최초상장주식수 (주)'],
      dtype='object')

In [22]:
kosdaq_df_공모가 = kosdaq_df1[['회사명', '상장일', '공모가 (원)']]
kosdaq_df_공모가.head()

        회사명         상장일 공모가 (원)
0     파인메딕스  2024-12-26  10,000
1   쓰리에이로직스  2024-12-24  11,000
2  신한제14호스팩  2024-12-23   2,000
3  키움제10호스팩  2024-12-20   2,000
4  온코닉테라퓨틱스  2024-12-19  13,000

In [23]:
kosdaq_df2 = pd.read_csv('../data/TS2000_주가/KOSDAQ_881_stock_data.csv')
kosdaq_df2.head()

C:\Users\Ph.D.Huh\AppData\Local\Temp\ipykernel_82100\1711967231.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  kosdaq_df2 = pd.read_csv('../data/TS2000_주가/KOSDAQ_881_stock_data.csv')

,회사명,거래소코드,회계년도,종목코드(축약),매매년월일,상장주식수(주),액면가(원),시가(원),고가(원),종가(원),거래량(주),거래대금(원)
0,가온칩스,399720,2022/05/20,399720,2022/05/20,"11,488,320",500,"24,150","30,500","27,100","19,492,306","499,287,960,850"
1,가온칩스,399720,2022/05/23,399720,2022/05/23,"11,488,320",500,"26,400","32,000","26,500","11,860,501","351,710,373,200"
2,가온칩스,399720,2022/05/24,399720,2022/05/24,"11,488,320",500,"26,650","31,500","30,500","9,796,109","283,808,502,900"
3,가온칩스,399720,2022/05/25,399720,2022/05/25,"11,488,320",500,"29,650","29,900","28,200","2,555,025","73,653,148,400"
4,가온칩스,399720,2022/05/26,399720,2022/05/26,"11,488,320",500,"28,550","29,650","27,000","1,966,784","56,029,873,850"

In [24]:
kosdaq_df2.columns

Index(['회사명', '거래소코드', '회계년도', '종목코드(축약)', '매매년월일', '상장주식수(주)', '액면가(원)',
       '시가(원)', '고가(원)', '종가(원)', '거래량(주)', '거래대금(원)'],
      dtype='object')

In [26]:
kosdaq_df_종가 = kosdaq_df2[['회사명', '회계년도', '종가(원)']]
kosdaq_df_종가.head()

    회사명        회계년도   종가(원)
0  가온칩스  2022/05/20  27,100
1  가온칩스  2022/05/23  26,500
2  가온칩스  2022/05/24  30,500
3  가온칩스  2022/05/25  28,200
4  가온칩스  2022/05/26  27,000